# Generated by Django 2.2.7 on 2019-11-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsignapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='mobile',
            new_name='phone_num',
        ),
    ]
